### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by rama41222** [rama41222/GimmikStore#2]
- [ ] Fix the ui issue on the model window - When the user taps on a search result, the app information is displayed on a model view. But the UI has bugs.

**Comment by AfaqYousafzai** [comment]
I can fix this issue. I have my sample project somehow similar to this issue as well.

**Comment by rama41222** [comment]
@AfaqYousafzai You can give it a try

**Comment by rama41222** [comment]
@ftp27 Great work
